### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-gobstones-server#3]
We should support syntax higlighting for both the editor ([Ace](ace.c9.io)) and the submission ([Rouge gem](https://github.com/jneen/rouge)).

This is what we have now:
- [Gobstones' BNF](http://www.gobstones.org/?wpdmact=process&did=Ny5ob3RsaW5r)
- **Ace:** [our fork](https://github.com/uqbar-project/ace), [the documentation that tells how to create a new highlighter](http://ace.c9.io/#nav=higlighter)
- **Rouge:** [the documentation that tells how to create a new highlighter](https://github.com/jneen/rouge#using-the-lexer-dsl)

**Comment by faloi** [comment]
@fedescarpa? @mdumrauf? @leansh?

**Comment by AlvarezAriel** [comment]
Added gobstones mode to our Ace fork, with basic support for keywords such as constants, control declarations and native functions.

**Comment by flbulgarelli** [comment]
Awesome!

**Comment by flbulgarelli** [comment]
@AlvarezAriel is there any way of using that fork? Or are you going to add more features soon and then pull request into ACE?

**Comment by faloi** [comment]
I'm working on that right now, ping me if you wanna help :smile:

**Comment by faloi** [comment]
Thanks to @javierfernandes this is solved. Closing.
