### ISSUE TITLE
Empty error message for syntax error

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-gobstones-server#54]
View http://es.mumuki.io/admin/submissions/40250

![image](https://cloud.githubusercontent.com/assets/1585835/9484857/47b77d0a-4b88-11e5-9446-fbd2245f4a36.png)

**Comment by gcrespi** [comment]
I think that problem is associated with this one-> https://github.com/gobstones/PyGobstones-Lang/issues/13

**Comment by faloi** [comment]
Could be, but I think the error `'NoneType' object has no attribute 'children'` should raise instead of an empty message. Could you try the example that appears on the issue?

**Comment by gcrespi** [comment]
Fixed in the new version of py-gobstones
