### ISSUE TITLE
Wrong title format displayed in result

### ISSUE THREAD

**Issue by matiasfmartino** [mumuki/mumuki-gobstones-server#69]
With the new structured output, the runner shows a tick/cross per example when it succeed/fails.

But the format is not correct, it shows the header tag like this:

![sin titulo](https://cloud.githubusercontent.com/assets/8515210/10871538/d23fa950-80c8-11e5-9ad2-61e1fc36e017.png)

And if the example has no title, it shows the tick/cross without any description:

![sin titulo2](https://cloud.githubusercontent.com/assets/8515210/10871566/2f375a68-80c9-11e5-9cfb-87d45559ab98.png)

I think we could generate a generic title, e.g. "Ejemplo #{example_number}" or something like that.

**Comment by faloi** [comment]
Ok, but the second problem should be addressed on each exercise. Perhaps the default should be included in the platform... @flbulgarelli?

**Comment by flbulgarelli** [comment]
Yes, the second problem may be resolved by generating a default message. 

The first problem is simple to resolve: just we need to remove HTML tags from sample title

**Comment by matiasfmartino** [comment]
The first problem was resolved in uqbar-project/stones-spec#35

**Comment by faloi** [comment]
And the other should be addressed directly on the platform.

**Comment by matiasfmartino** [comment]
And the second is addressed in mumuki/mumuki-platform#360
